### ISSUE TITLE
不太会用，刚接触python 这个我要问的问题放在那里 ，是python xiaoiceapi.py  “你是谁”，求指教

### ISSUE THREAD

**Issue by 1158114251** [yanwii/msxiaoiceapi#1]

**Comment by yanwii** [comment]
如果你想使用url链接式的，就直接打开浏览器http://127.0.0.1:5000/?que=%E4%B8%8D%E5%BC%80%E5%BF%83   
  

如果你只想调用这个方法  
将xb.api()直接换成xb.chat("your questions") 即可

**Comment by 1158114251** [comment]
感谢回复，已明白，原来是您为了操作方便，写了个服务器，以网页的形式提交内容。个人刚接触，没看懂搞笑了。

**Comment by yanwii** [comment]
互相学习！
:)
