### ISSUE TITLE
大神，看到你的项目有点问题想咨询下 第二次请求getbyid 拿不到返回数据

### ISSUE THREAD

**Issue by Killua67** [yanwii/msxiaoiceapi#4]

**Comment by Killua67** [comment]
现在的情况是，我第二个请求总是拿不到response 提示的是请求丢失，Connection aborted。好像它直接把结果返回到了 微博私信的对话框了，程序里面就拿不到返回的数据。你知道这是为什么吗

**Comment by yanwii** [comment]
领养了小冰吗？
把错误贴出来看看。

**Comment by Killua67** [comment]
嘿嘿。我找到原因了，不应该全部复制header，不知道是我的chrome还是怎么回事，删除几个header参数，保留你示例里面的变量就可以了。估计应该是某个参数 配置了什么，只把信息返回了微博私信，Python就接受不到

**Comment by Yaque** [comment]
现在这个还能用吗，我刚刚闲的慌拽了这个，但发现不行，我也用的谷歌，等会安妮说的试试。
